version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: acergiyen
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

  simulator:
    image: simulator:latest
    container_name: simulator
    ports:
      - "8080:8080"
    depends_on:
      - postgres   

